// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: reservation.proto

package reservation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReservationService_CreateRestaurant_FullMethodName  = "/reservation.ReservationService/CreateRestaurant"
	ReservationService_UpdateRestaurant_FullMethodName  = "/reservation.ReservationService/UpdateRestaurant"
	ReservationService_RemoveRestaurant_FullMethodName  = "/reservation.ReservationService/RemoveRestaurant"
	ReservationService_GetAllRestaurants_FullMethodName = "/reservation.ReservationService/GetAllRestaurants"
	ReservationService_GetRestaurantById_FullMethodName = "/reservation.ReservationService/GetRestaurantById"
)

// ReservationServiceClient is the client API for ReservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReservationServiceClient interface {
	CreateRestaurant(ctx context.Context, in *CreateRestaurantReq, opts ...grpc.CallOption) (*CreateRestaurantRes, error)
	UpdateRestaurant(ctx context.Context, in *UpdateRestaurantReq, opts ...grpc.CallOption) (*UpdateRestaurantRes, error)
	RemoveRestaurant(ctx context.Context, in *RemoveRestaurantReq, opts ...grpc.CallOption) (*RemoveRestaurantRes, error)
	GetAllRestaurants(ctx context.Context, in *GetRestaurantsReq, opts ...grpc.CallOption) (*GetRestaurantsRes, error)
	GetRestaurantById(ctx context.Context, in *GetRestaurantReq, opts ...grpc.CallOption) (*GetRestaurantRes, error)
}

type reservationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReservationServiceClient(cc grpc.ClientConnInterface) ReservationServiceClient {
	return &reservationServiceClient{cc}
}

func (c *reservationServiceClient) CreateRestaurant(ctx context.Context, in *CreateRestaurantReq, opts ...grpc.CallOption) (*CreateRestaurantRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRestaurantRes)
	err := c.cc.Invoke(ctx, ReservationService_CreateRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) UpdateRestaurant(ctx context.Context, in *UpdateRestaurantReq, opts ...grpc.CallOption) (*UpdateRestaurantRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRestaurantRes)
	err := c.cc.Invoke(ctx, ReservationService_UpdateRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) RemoveRestaurant(ctx context.Context, in *RemoveRestaurantReq, opts ...grpc.CallOption) (*RemoveRestaurantRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRestaurantRes)
	err := c.cc.Invoke(ctx, ReservationService_RemoveRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) GetAllRestaurants(ctx context.Context, in *GetRestaurantsReq, opts ...grpc.CallOption) (*GetRestaurantsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantsRes)
	err := c.cc.Invoke(ctx, ReservationService_GetAllRestaurants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) GetRestaurantById(ctx context.Context, in *GetRestaurantReq, opts ...grpc.CallOption) (*GetRestaurantRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantRes)
	err := c.cc.Invoke(ctx, ReservationService_GetRestaurantById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReservationServiceServer is the server API for ReservationService service.
// All implementations should embed UnimplementedReservationServiceServer
// for forward compatibility.
type ReservationServiceServer interface {
	CreateRestaurant(context.Context, *CreateRestaurantReq) (*CreateRestaurantRes, error)
	UpdateRestaurant(context.Context, *UpdateRestaurantReq) (*UpdateRestaurantRes, error)
	RemoveRestaurant(context.Context, *RemoveRestaurantReq) (*RemoveRestaurantRes, error)
	GetAllRestaurants(context.Context, *GetRestaurantsReq) (*GetRestaurantsRes, error)
	GetRestaurantById(context.Context, *GetRestaurantReq) (*GetRestaurantRes, error)
}

// UnimplementedReservationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReservationServiceServer struct{}

func (UnimplementedReservationServiceServer) CreateRestaurant(context.Context, *CreateRestaurantReq) (*CreateRestaurantRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestaurant not implemented")
}
func (UnimplementedReservationServiceServer) UpdateRestaurant(context.Context, *UpdateRestaurantReq) (*UpdateRestaurantRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestaurant not implemented")
}
func (UnimplementedReservationServiceServer) RemoveRestaurant(context.Context, *RemoveRestaurantReq) (*RemoveRestaurantRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRestaurant not implemented")
}
func (UnimplementedReservationServiceServer) GetAllRestaurants(context.Context, *GetRestaurantsReq) (*GetRestaurantsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRestaurants not implemented")
}
func (UnimplementedReservationServiceServer) GetRestaurantById(context.Context, *GetRestaurantReq) (*GetRestaurantRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantById not implemented")
}
func (UnimplementedReservationServiceServer) testEmbeddedByValue() {}

// UnsafeReservationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReservationServiceServer will
// result in compilation errors.
type UnsafeReservationServiceServer interface {
	mustEmbedUnimplementedReservationServiceServer()
}

func RegisterReservationServiceServer(s grpc.ServiceRegistrar, srv ReservationServiceServer) {
	// If the following call pancis, it indicates UnimplementedReservationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReservationService_ServiceDesc, srv)
}

func _ReservationService_CreateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestaurantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).CreateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_CreateRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).CreateRestaurant(ctx, req.(*CreateRestaurantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_UpdateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRestaurantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).UpdateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_UpdateRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).UpdateRestaurant(ctx, req.(*UpdateRestaurantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_RemoveRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRestaurantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).RemoveRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_RemoveRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).RemoveRestaurant(ctx, req.(*RemoveRestaurantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_GetAllRestaurants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).GetAllRestaurants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_GetAllRestaurants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).GetAllRestaurants(ctx, req.(*GetRestaurantsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_GetRestaurantById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).GetRestaurantById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReservationService_GetRestaurantById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).GetRestaurantById(ctx, req.(*GetRestaurantReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ReservationService_ServiceDesc is the grpc.ServiceDesc for ReservationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReservationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reservation.ReservationService",
	HandlerType: (*ReservationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRestaurant",
			Handler:    _ReservationService_CreateRestaurant_Handler,
		},
		{
			MethodName: "UpdateRestaurant",
			Handler:    _ReservationService_UpdateRestaurant_Handler,
		},
		{
			MethodName: "RemoveRestaurant",
			Handler:    _ReservationService_RemoveRestaurant_Handler,
		},
		{
			MethodName: "GetAllRestaurants",
			Handler:    _ReservationService_GetAllRestaurants_Handler,
		},
		{
			MethodName: "GetRestaurantById",
			Handler:    _ReservationService_GetRestaurantById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reservation.proto",
}
