// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/telemedicine.proto

package pbtelemedicine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemedicineService_Consult_FullMethodName = "/telemedicine.TelemedicineService/Consult"
)

// TelemedicineServiceClient is the client API for TelemedicineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemedicineServiceClient interface {
	Consult(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsultationMessage, ConsultationMessage], error)
}

type telemedicineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemedicineServiceClient(cc grpc.ClientConnInterface) TelemedicineServiceClient {
	return &telemedicineServiceClient{cc}
}

func (c *telemedicineServiceClient) Consult(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsultationMessage, ConsultationMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemedicineService_ServiceDesc.Streams[0], TelemedicineService_Consult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsultationMessage, ConsultationMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemedicineService_ConsultClient = grpc.BidiStreamingClient[ConsultationMessage, ConsultationMessage]

// TelemedicineServiceServer is the server API for TelemedicineService service.
// All implementations must embed UnimplementedTelemedicineServiceServer
// for forward compatibility.
type TelemedicineServiceServer interface {
	Consult(grpc.BidiStreamingServer[ConsultationMessage, ConsultationMessage]) error
	mustEmbedUnimplementedTelemedicineServiceServer()
}

// UnimplementedTelemedicineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemedicineServiceServer struct{}

func (UnimplementedTelemedicineServiceServer) Consult(grpc.BidiStreamingServer[ConsultationMessage, ConsultationMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Consult not implemented")
}
func (UnimplementedTelemedicineServiceServer) mustEmbedUnimplementedTelemedicineServiceServer() {}
func (UnimplementedTelemedicineServiceServer) testEmbeddedByValue()                             {}

// UnsafeTelemedicineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemedicineServiceServer will
// result in compilation errors.
type UnsafeTelemedicineServiceServer interface {
	mustEmbedUnimplementedTelemedicineServiceServer()
}

func RegisterTelemedicineServiceServer(s grpc.ServiceRegistrar, srv TelemedicineServiceServer) {
	// If the following call pancis, it indicates UnimplementedTelemedicineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemedicineService_ServiceDesc, srv)
}

func _TelemedicineService_Consult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemedicineServiceServer).Consult(&grpc.GenericServerStream[ConsultationMessage, ConsultationMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemedicineService_ConsultServer = grpc.BidiStreamingServer[ConsultationMessage, ConsultationMessage]

// TelemedicineService_ServiceDesc is the grpc.ServiceDesc for TelemedicineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemedicineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemedicine.TelemedicineService",
	HandlerType: (*TelemedicineServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consult",
			Handler:       _TelemedicineService_Consult_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/telemedicine.proto",
}
